server/config/routes.rb
Blusteromatic::Application.routes.draw do
  resources :groups


  namespace :api do
    resource :node do
      post "heartbeat"
      get "get_job"
      post "update_job"
      post "finish_job"
      post "error_job"
    end
  end

  resources :blender_configs do
    get :clone
  end

  resources :jobs do
    get :assign
    get :reassign
    get :reset
    resources :renders
  end

  devise_for :users

  resources :users

  resources :nodes do
    get :activate
    get :deactivate
    get :pause
  end









  root :to => 'application#index'


end

server/app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :filename, :job_name, :name, :node_id, :node_status, :priority, :status, :user_id, :render_type, :render_frame_start, :render_frame_stop, :render_engine, :dot_blend, :compute, :dot_blend_cache, :blender_config_id, :group

  extend FriendlyId
  friendly_id :name, use: :slugged

  # job_name : "name(sanitized)_render_type_start_stop_engine" like "my_job_01_ANIM_0_150_CYCLES"

  belongs_to :user
  belongs_to :node
  has_many :renders
  belongs_to :blender_config

  mount_uploader :dot_blend, DotBlendUploader

  validates_presence_of :dot_blend, :render_engine, :render_frame_stop, :render_frame_start, :render_type, :priority, :name, :blender_config_id
  before_validation :compute_hash
  before_save :save_filename
  before_create :default_status

  def compute_hash
    if self.dot_blend.file
      self.md5 = Digest::MD5.hexdigest(self.dot_blend.read)
    else
      self.md5 = ""
    end
  end
  def save_filename
    self.filename = self.dot_blend.file.filename
  end
  def default_status
    self.status = "waiting"
    self.node_status = "waiting"
  end
end

server/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  load_and_authorize_resource

  # GET /jobs
  # GET /jobs.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    @job.user = current_user

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  def reassign
    # We just call assign, but we reset statues before that
    @job = Job.find(params[:job_id])
    @job.default_status
    @job.save
    assign
  end

  def assign
    @job = Job.find(params[:job_id])
    # find a node compatible with this kind of caracteristics : CPU or GPU, RENDER_ENGINE
    the_node = nil
    Node.where(:validated => true).each do |node|
      # Skip inactive and not alive nodes
      next if !node.alive?
      # Skip not matching blender engine
      next if !node.blender_engines.split(",").include? @job.render_engine
      # Skip not matching compute capabilities
      next if !node.compute.split(",").include? @job.compute
      # Skip if the user doesn't have the right to use the node
      next if !can? :use, node
      # If we are here, the node match all points \o/
      the_node = node
      break
    end

    if the_node
      @job.node = the_node
      @job.save
      redirect_to @job, :notice => "Job assigned to #{the_node.name}."
    else
      redirect_to root_url, :notice => "Can't find active node with #{@job.render_engine},#{@job.compute} capabilities."
    end
  end

  def reset
    @job = Job.find(params[:job_id])
    @job.default_status
    @job.node = nil
    @job.save
    redirect_to @job
  end

end

server/app/helpers/jobs_helper.rb
module JobsHelper
end

server/app/views/jobs/_form.html.erb
<%= form_for @job, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :render_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :render_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :render_frame_start, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :render_frame_start, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :render_frame_stop, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :render_frame_stop, :class => 'number_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :render_engine, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :render_engine, options_for_select(Node.blender_engines(1), :selected => "CYCLES") %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :compute, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :compute, options_for_select(Node.computes(1), :selected => "GPU") %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :dot_blend, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :dot_blend, :class => 'file_field' %>
      <%= f.hidden_field :dot_blend_cache %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :blender_config_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :blender_config_id, BlenderConfig.all, :id, :name, :class => "number_field", :include_blank => true %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :group, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :group, options_for_select(Group.jobs_for_coll, :selected => "8") %>
    </div>
  </div>



  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                jobs_path, :class => 'btn' %>
  </div>
<% end %>

server/app/views/jobs/_list.html.erb
<table class="table table-striped table-condensed">
  <caption>Jobs</caption>
  <thead>
    <tr>
      <th>Name</th>
      <th>Engine</th>
      <th>Compute</th>
      <th>Type</th>
      <th>Node</th>
      <th>Render Time</th>
      <th>Visibility</th>
      <th>Status</th>
      <%- if current_user %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <%- @jobs.each do |job| %>
      <tr>
        <td><%= link_to job.name, job %></td>
        <td><%= job.render_engine %></td>
        <td><%= job.compute %></td>
        <%- if job.render_type == 'SINGLE' %>
          <td><%= job.render_type %></td>
        <% else %>
          <td>
            <%= job.render_type %> <%= job.render_frame_start %> - <%= job.render_frame_stop %>
          </td>
        <% end %>
        <%- if job.node %>
          <td><%= job.node.name %></td>
        <% else %>
          <td>N/A</td>
        <% end %>
        <td><%= job.renders.last.render_time if job.renders.last %></td>
        <td><%= Group.get_sym(job.group) %></td>
        <td>
          Job: <%= job.status || "N/A" %><br />
          Node: <%= job.node_status || "N/A" %>
        </td>
        <%- if current_user %>
          <td>
            <div class="btn-group">
              <%- if !job.node %>
                <%= link_to "assign", job_assign_url(job), :class => "btn btn-mini btn-success" %>
              <% end %>
              <%= link_to "delete", job_path(job), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
            </div>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

server/app/views/jobs/edit.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

server/app/views/jobs/index.html.erb
<%= render :partial => 'list' %>

server/app/views/jobs/new.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

server/app/views/jobs/show.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <%- if current_user %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                job_path(@job),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger btn-mini pull-right' %>
    <%- if !@job.node or @job.status == 'finished' %>
      <%= link_to "reassign to a node", job_reassign_url(@job), :class => "btn btn-mini btn-success" %>
    <% end %>
  <% end %>

  <h3><%= @job.name %></h3>

</div>

<table class="table table-bordered">
  <tr>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:node) %></th>
    <th><%= model_class.human_attribute_name(:node_status) %></th>
    <th><%= model_class.human_attribute_name(:status) %></th>
    <th><%= model_class.human_attribute_name(:render_type) %></th>
    <th><%= model_class.human_attribute_name(:render_frame_start) %></th>
    <th><%= model_class.human_attribute_name(:render_frame_stop) %></th>
    <th><%= model_class.human_attribute_name(:render_engine) %></th>
    <th><%= model_class.human_attribute_name(:compute) %></th>
    <th><%= model_class.human_attribute_name(:blender_config) %></th>
    <th><%= model_class.human_attribute_name(:visibility) %></th>
  </tr>
  <tr>
    <td><%= @job.name %></td>
    <%- if @job.node %>
      <td><%= @job.node.name %></td>
    <% else %>
      <td></td>
    <% end %>
    <td><%= @job.node_status %></td>
    <td><%= @job.status %></td>
    <td><%= @job.render_type %></td>
    <td><%= @job.render_frame_start %></td>
    <td><%= @job.render_frame_stop %></td>
    <td><%= @job.render_engine %></td>
    <td><%= @job.compute %></td>
    <td><%= link_to @job.blender_config.name, @job.blender_config %></td>
    <td><%= Group.get_sym(@job.group) %></td>
  </tr>
</table>

<br />

<ul class="nav nav-tabs">
  <li class="active"><a href="#console" data-toggle="tab">Console</a></li>
  <li><a href="#renders" data-toggle="tab">Render outputs</a></li>
  <%- if current_user %>
    <li><a href="#emergency" data-toggle="tab">Emergency</a></li>
  <% end %>
</ul>

<div class="tab-content">

  <div class="tab-pane active" id="console">
    <pre><%= @job.log || "No log right now." %></pre>
  </div>

  <div class="tab-pane" id="renders">
    &raquo; <%= link_to "Show all renders", job_renders_url(@job) %>
    <br />
    <br />
    <ul class="thumbnails">
      <%- @job.renders.order("created_at DESC").limit(5).each do |r| %>
        <li class="span3">
          <div class="thumbnail">
            <%= r.id %> - <%= r.created_at %>
            <a href="<%= r.output %>">
              <img src="<%= r.output %>" alt="<%= r.filename %>" />
            </a>
            <p>
              Render time: <%= r.render_time %>
              <br />
              <%= link_to "Show render with log", job_render_url(@job, r), :class => "btn btn-mini" %>
            </p>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

  <%- if current_user %>
    <div class="tab-pane" id="emergency">

      If the job isn't updating anymore : please check on the node side
      ! and if the node is really crashed, you can reset here the
      status.

      <br /><br />

      <%= link_to t('Reset statues', :default => t("helpers.links.reset_statues")),
          job_reset_url(@job),
          :data => { :confirm => t('.confirm', :default =>
          t("helpers.links.confirm_reset_job", :default => 'Are you REALLY sure? This can lead to serious problems with your job !')) },
          :class => 'btn btn-danger btn-mini' %>

    </div>
  <% end %>

</div>