server/config/routes.rb
Blusteromatic::Application.routes.draw do
  resources :groups


  namespace :api do
    resource :node do
      post "heartbeat"
      get "get_job"
      post "update_job"
      post "finish_job"
      post "error_job"
    end
  end

  resources :blender_configs do
    get :clone
  end

  resources :jobs do
    get :assign
    get :reassign
    get :reset
    resources :renders
  end

  devise_for :users

  resources :users

  resources :nodes do
    get :activate
    get :deactivate
    get :pause
  end









  root :to => 'application#index'


end

server/app/models/blender_config.rb
class BlenderConfig < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :name, :description, :config, :public, :user_id

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  belongs_to :job

  validates_presence_of :name, :config

end

server/app/controllers/blender_configs_controller.rb
class BlenderConfigsController < ApplicationController
  before_filter :authenticate_user!

  # GET /blender_configs
  # GET /blender_configs.json
  def index
    @blender_configs = BlenderConfig.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blender_configs }
    end
  end

  # GET /blender_configs/1
  # GET /blender_configs/1.json
  def show
    @blender_config = BlenderConfig.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blender_config }
    end
  end

  # GET /blender_configs/new
  # GET /blender_configs/new.json
  def new
    @blender_config = BlenderConfig.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blender_config }
    end
  end

  def clone
    @blender_config = BlenderConfig.new
    clone = BlenderConfig.find(params[:blender_config_id])
    @blender_config.name = clone.name
    @blender_config.description = clone.description
    @blender_config.config = clone.config

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blender_config }
    end
  end

  # GET /blender_configs/1/edit
  def edit
    @blender_config = BlenderConfig.find(params[:id])
  end

  # POST /blender_configs
  # POST /blender_configs.json
  def create
    @blender_config = BlenderConfig.new(params[:blender_config])

    respond_to do |format|
      if @blender_config.save
        format.html { redirect_to @blender_config, notice: 'Blender config was successfully created.' }
        format.json { render json: @blender_config, status: :created, location: @blender_config }
      else
        format.html { render action: "new" }
        format.json { render json: @blender_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blender_configs/1
  # PUT /blender_configs/1.json
  def update
    @blender_config = BlenderConfig.find(params[:id])

    respond_to do |format|
      if @blender_config.update_attributes(params[:blender_config])
        format.html { redirect_to @blender_config, notice: 'Blender config was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blender_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blender_configs/1
  # DELETE /blender_configs/1.json
  def destroy
    @blender_config = BlenderConfig.find(params[:id])
    @blender_config.destroy

    respond_to do |format|
      format.html { redirect_to blender_configs_url }
      format.json { head :no_content }
    end
  end
end

server/app/helpers/blender_configs_helper.rb
module BlenderConfigsHelper
end

server/app/views/blender_configs/_form.html.erb
<%= form_for @blender_config, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field span7',
      :placeholder => "Name of your config, like 'HD with 200 samples'" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area span7', :rows => 4, :placeholder => "A little text to explain your config specifics" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :config, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :config, :class => 'text_area span7', :rows => 20, :placeholder => "Here is the config content, please double-check for errors !"  %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                blender_configs_path, :class => 'btn' %>
  </div>
<% end %>

server/app/views/blender_configs/clone.html.erb
<%- model_class = BlenderConfig -%>
<div class="page-header">
  <h1>Clone config</h1>
</div>
<%= render :partial => 'form' %>

server/app/views/blender_configs/edit.html.erb
<%- model_class = BlenderConfig -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

server/app/views/blender_configs/index.html.erb
<%- model_class = BlenderConfig -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @blender_configs.each do |blender_config| %>
      <tr>
        <td><%= link_to blender_config.id, blender_config_path(blender_config) %></td>
        <td><%= link_to blender_config.name, blender_config_path(blender_config) %></td>
        <td><%= blender_config.description %></td>
        <td>
          <%= link_to t('clone and edit', :default => t("helpers.links.clone_and_edit")),
                      blender_config_clone_path(blender_config),
                      :class => 'btn btn-mini' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_blender_config_path(blender_config), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      blender_config_path(blender_config),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_blender_config_path,
            :class => 'btn btn-primary' %>

server/app/views/blender_configs/new.html.erb
<%- model_class = BlenderConfig -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

server/app/views/blender_configs/show.html.erb
<div class="page-header">
  <h3><%= @blender_config.name %></h3>
</div>

<p>
  <%= @blender_config.description %>
</p>

<br />

<pre><%= @blender_config.config %></pre>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              blender_configs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_blender_config_path(@blender_config), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              blender_config_path(@blender_config),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>