server/config/routes.rb
Blusteromatic::Application.routes.draw do
  resources :groups


  namespace :api do
    resource :node do
      post "heartbeat"
      get "get_job"
      post "update_job"
      post "finish_job"
      post "error_job"
    end
  end

  resources :blender_configs do
    get :clone
  end

  resources :jobs do
    get :assign
    get :reassign
    get :reset
    resources :renders
  end

  devise_for :users

  resources :users

  resources :nodes do
    get :activate
    get :deactivate
    get :pause
  end









  root :to => 'application#index'


end

server/app/views/shared/_footer.html.erb
<div class="container footer">
	<div class="content">
		<div class="row">
			<div class="span11">
				<p>
                                  <a href="http://github.com/rhaamo/blusteromatic">
                                  <%= t 'footer.running',
                                  :version => "v0.3 rev
                                  #{BLUSTEROMATIC_VERSION}" %>
                                  </a>
                                  <br />
                                </p>
			</div>
			<div class="span1">
				<%= link_to "http://rubyonrails.org/", :target => "_blank" do %>
				<%= image_tag "rails.png", :alt => "Rails powered !" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

server/app/views/shared/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
      </a>
      <%= link_to Settings.app_title || "Blusteromatic", root_url, :class => "brand" %>
      <div class="nav-collapse">
	      <ul class="nav">
	        <li><%= link_to "Jobs list", root_url %></li>
          <%- if current_user && current_user.admin? %>
            <li><%= link_to "Blender configs", blender_configs_url %></li>
            <li><%= link_to "Groups", groups_url %></li>
          <% end %>
          <%- if current_user %>
            <li><%= link_to "New job", new_job_url %></li>
          <% end %>
	      </ul> <!-- ul nav -->

        <%- if current_user %>
  	      <div class="btn-group pull-right">
            <%= link_to current_user, :class => "btn btn-primary" do %>
  	          <i class="icon-user icon-white"></i>
  	          <%= current_user.login %> (<%= Group.get_sym(current_user.role) %>)
            <% end %>

            <%= link_to "#", :class => "btn btn-info dropdown-toggle", :"data-toggle" => "dropdown" do %>
  	          <span class="caret"></span>
            <% end %>

            <ul class="dropdown-menu">
  	          <li>
  		          <%= link_to edit_user_path(current_user) do %>
  		            <i class="icon-pencil"></i>
  		            <%= t 'header.edit_profile' %>
  		          <% end %>
  	          </li>

  	          <li class="divider"></li>
  	          <li>
  		          <%= link_to destroy_user_session_path, :method => :delete do %>
  		            <i class="icon-off"></i>
  		            <%= t 'header.logout' %>
  		          <% end %>
  	          </li>
  	        </ul>
          </div>
          <% else %>
            <div class="btn-group pull-right">
              <%= link_to new_user_session_url, :class => "btn btn-primary" do %>
                <i class="icon-user icon-white"></i>
                Sign In
              <% end %>
            </div>
          <% end %>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>