server/config/routes.rb
Blusteromatic::Application.routes.draw do
  resources :groups


  namespace :api do
    resource :node do
      post "heartbeat"
      get "get_job"
      post "update_job"
      post "finish_job"
      post "error_job"
    end
  end

  resources :blender_configs do
    get :clone
  end

  resources :jobs do
    get :assign
    get :reassign
    get :reset
    resources :renders
  end

  devise_for :users

  resources :users

  resources :nodes do
    get :activate
    get :deactivate
    get :pause
  end









  root :to => 'application#index'


end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  check_authorization :unless => :ohai_can_you_please_check_if_the_controller_name_is_application_kthxbye?


  def index
    @jobs = Job.accessible_by(current_ability)
    @nodes = Node.accessible_by(current_ability)

    if current_user
      render 'index'
    else
      render 'jobs/_list'
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  private
  def ohai_can_you_please_check_if_the_controller_name_is_application_kthxbye?
    return true if controller_path.start_with?("api/")
    if devise_controller?
      return true
    else
      controller_name == "application"
    end
  end
end

server/app/helpers/application_helper.rb
module ApplicationHelper
end

server/app/views/application/index.html.erb
<div class="row">
  <div class="span12">
    <%= render :partial => 'jobs/list' %>
  </div>
</div>

<br />

<div class="row">
  <div class="span12">
    <table class="table table-striped table-condensed">
      <caption>Nodes</caption>
      <thead>
        <tr>
          <th>Name</th>
          <th>OS</th>
          <th>Engines</th>
          <th>Compute</th>
          <th>Last ping</th>
          <th>Blender version</th>
          <th>Group</th>
          <th>Paused</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <%- @nodes.each do |node| %>
          <%- if !node.alive? %>
            <tr class="row_red">
          <% else %>
            <tr>
          <% end %>
            <td><%= node.name %></td>
            <td><%= node.os %></td>
            <td><%= node.blender_engines %></td>
            <td><%= node.compute %></td>
            <td><%= node.last_ping %></td>
            <td><%= node.blender_version %></td>
            <td><%= Group.get_sym(node.group) %></td>
            <td><%= node.paused %></td>
            <td>
              <div class="btn-group">
              <%- if node.validated != 1 %>
                <%= link_to "activate", node_activate_url(node), :class => "btn btn-mini btn-success" %>
              <% end %>
              <%= link_to "delete", node_path(node), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
              <%= link_to "pause", node_pause_url(node), :class => "btn btn-mini btn-info" %>
              </div>
            </td>
          </tr>
        <% end %>

        </tr>
      </tbody>
    </table>
  </div>
</div>